<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TSDeudaCamineraFallar</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>7506bd7e-1b17-4b98-af38-138675d8c5ec</testSuiteGuid>
   <testCaseLink>
      <guid>6ab456b1-a27e-4b75-9092-f93da096f65b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WSDeudas/WSDeudasFail/obo deudas fail</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7a1f008a-f4da-4b04-a244-1f104a0a9456</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/FALLA CUIT MultaCaminera</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7a1f008a-f4da-4b04-a244-1f104a0a9456</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CUIT</value>
         <variableId>57b986f0-fa62-452e-ba9c-d58249376046</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7117d48-6c5e-4be4-aca8-6e644ec7ca40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78f13fe8-38bd-4e69-8820-50692eb2e074</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
