<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS inmueble (CUIT)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>47f693ea-f9ac-4682-b973-305d90e4b669</testSuiteGuid>
   <testCaseLink>
      <guid>afc1178d-16b4-446d-8d2f-f410e827dc53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WSInmuebles/WSInmueblesCUIT/afip mi inmueble ok (CUIT)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fea35a5a-a62a-4d53-8dd1-04cb4b861ceb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/WSInmuebles/Inmuebles(CUIT)</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fea35a5a-a62a-4d53-8dd1-04cb4b861ceb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Inmuebles</value>
         <variableId>31bd30d4-96ac-45b1-8f43-d7cf9448246a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b50e6a7-6183-49e6-a71e-5519e7625fab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d38813ac-04a7-43d8-8c97-69e8d64fe415</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e055232-f3e0-42a0-96d6-0cf2065153f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b125c1ac-7f75-475e-ba3d-e94f890cc668</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
